title: Dr. Christina Ertural | Scientist
email: christina.ertural(at)bam.de
description: Personal site about my research..
show_downloads: false
google_analytics:
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: cer5814012
github_username: QuantumChemist
# Build settings
markdown: kramdown
theme: jekyll-theme-hacker
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
icon:
